# Generated by Django 3.1.1 on 2020-09-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Name',
            new_name='name',
        ),
    ]
