# Generated by Django 3.1.1 on 2020-09-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mediterranean'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(null='True', upload_to=''),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='ketogenic',
            name='img',
            field=models.ImageField(null='True', upload_to=''),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='mediterranean',
            name='img',
            field=models.ImageField(null='True', upload_to=''),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='paleo',
            name='img',
            field=models.ImageField(null='True', upload_to=''),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vegan',
            name='img',
            field=models.ImageField(null='True', upload_to=''),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vegetarian',
            name='img',
            field=models.ImageField(null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
