# Generated by Django 3.1.1 on 2020-09-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200927_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(default='static/images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ketogenic',
            name='img',
            field=models.ImageField(default='static/images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mediterranean',
            name='img',
            field=models.ImageField(default='static/images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='paleo',
            name='img',
            field=models.ImageField(default='static/images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vegan',
            name='img',
            field=models.ImageField(default='static/images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vegetarian',
            name='img',
            field=models.ImageField(default='images/DIET3.jpg', upload_to='images'),
        ),
    ]
