# Generated by Django 3.1.1 on 2020-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200927_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='drop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicename', models.CharField(choices=[('light meal', 'light meal'), ('medium meal', 'medium meal'), ('heavy meal', 'heavy meal')], max_length=120)),
            ],
        ),
    ]
