# Generated by Django 3.1.3 on 2021-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_drop'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=30)),
                ('img', models.ImageField(default='static/images/DIET3.jpg', upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
