# Generated by Django 3.1.3 on 2021-03-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_foodrequest_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=10000)),
                ('productlink', models.CharField(default='NO LINK AVAILABLE', max_length=1000)),
                ('productimage', models.ImageField(default='images/dlogo.jpeg', upload_to='images')),
            ],
        ),
    ]
