# Generated by Django 3.1.3 on 2021-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210317_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='productprice',
            field=models.FloatField(default='0.0'),
        ),
    ]
