# Generated by Django 3.1.3 on 2021-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_shopper_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('bookauthor', models.CharField(max_length=100)),
                ('booklink', models.CharField(max_length=1000)),
                ('bookimage', models.ImageField(default='images/dlogo.jpeg', upload_to='images')),
            ],
        ),
    ]
