# Generated by Django 3.1.3 on 2021-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactfname', models.CharField(max_length=100)),
                ('contactlname', models.CharField(max_length=100)),
                ('contactsubject', models.CharField(max_length=1000)),
            ],
        ),
    ]
