# Generated by Django 3.1.3 on 2021-03-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactfname',
            new_name='FIRSTNAME',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactlname',
            new_name='LASTNAME',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactsubject',
            new_name='SUBJECT',
        ),
    ]
