# Generated by Django 3.1.3 on 2021-03-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210318_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(default='images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ketogenic',
            name='img',
            field=models.ImageField(default='images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mediterranean',
            name='img',
            field=models.ImageField(default='images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='paleo',
            name='img',
            field=models.ImageField(default='images/DIET3.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='vegan',
            name='img',
            field=models.ImageField(default='images/DIET3.jpg', upload_to='images'),
        ),
    ]
